In [6]:
import pandas as pd

pokemon_data = pd.read_csv('pokemon_data.csv' , index_col=0)
pokemon_data

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [2]:
fruits = pd.DataFrame({"Apples" : [131,71] , 'Mangos' : [23,41]} , index={"sales_2017" , "sales_2018"})
fruits

            Apples  Mangos
sales_2017     131      23
sales_2018      71      41

Reading Data in Pandas

In [19]:
# Read Headers
print(pokemon_data.columns)

# Reading Columns
print(pokemon_data['Name'][0:5])
# You can also pass parameter as the list of column names.
print(pokemon_data[['Name','HP','Type 1']])

Index(['Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
#
1                Bulbasaur
2                  Ivysaur
3                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object
                      Name  HP   Type 1
#
1                Bulbasaur  45    Grass
2                  Ivysaur  60    Grass
3                 Venusaur  80    Grass
3    VenusaurMega Venusaur  80    Grass
4               Charmander  39     Fire
..                     ...  ..      ...
719                Diancie  50     Rock
719    DiancieMega Diancie  50     Rock
720    HoopaHoopa Confined  80  Psychic
720     HoopaHoopa Unbound  80  Psychic
721              Volcanion  80     Fire

[800 rows x 3 columns]

In [23]:
# Read each row
print(pokemon_data.iloc[0])
# Gives me every info in the row 1

# Trick to iterate through every row and every info.
for index , row in pokemon_data.iterrows():
    print(index , row['Name'])

Name          Bulbasaur
Type 1            Grass
Type 2           Poison
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 1, dtype: object
1 Bulbasaur
2 Ivysaur
3 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
6 CharizardMega Charizard X
6 CharizardMega Charizard Y
7 Squirtle
8 Wartortle
9 Blastoise
9 BlastoiseMega Blastoise
10 Caterpie
11 Metapod
12 Butterfree
13 Weedle
14 Kakuna
15 Beedrill
15 BeedrillMega Beedrill
16 Pidgey
17 Pidgeotto
18 Pidgeot
18 PidgeotMega Pidgeot
19 Rattata
20 Raticate
21 Spearow
22 Fearow
23 Ekans
24 Arbok
25 Pikachu
26 Raichu
27 Sandshrew
28 Sandslash
29 Nidoran (Female)
30 Nidorina
31 Nidoqueen
32 Nidoran (Male)
33 Nidorino
34 Nidoking
35 Clefairy
36 Clefable
37 Vulpix
38 Ninetales
39 Jigglypuff
40 Wigglytuff
41 Zubat
42 Golbat
43 Oddish
44 Gloom
45 Vileplume
46 Paras
47 Parasect
48 Venonat
49 Venomoth
50 Diglett
51 Dugtrio
52 Meowth
53 Persian
54 Psyduck
55 Golduck
56 Mankey
57 Primeape
58 Growlithe
59 Arcanine
60 Poliwag
61 Poliwhirl
62 Poliwrath
63 Abra
64 Kadabra
65 Alakazam
65 AlakazamMega Alakazam
66 Machop
67 Machoke
68 Machamp
69 Bellsprout
70 Weepinbell
71 Victreebel
72 Tentacool
73 Tentacruel
74 Geodude
75 Graveler
76 Golem
77 Ponyta
78 Rapidash
79 Slowpoke
80 Slowbro
80 SlowbroMega Slowbro
81 Magnemite
82 Magneton
83 Farfetch'd
84 Doduo
85 Dodrio
86 Seel
87 Dewgong
88 Grimer
89 Muk
90 Shellder
91 Cloyster
92 Gastly
93 Haunter
94 Gengar
94 GengarMega Gengar
95 Onix
96 Drowzee
97 Hypno
98 Krabby
99 Kingler
100 Voltorb
101 Electrode
102 Exeggcute
103 Exeggutor
104 Cubone
105 Marowak
106 Hitmonlee
107 Hitmonchan
108 Lickitung
109 Koffing
110 Weezing
111 Rhyhorn
112 Rhydon
113 Chansey
114 Tangela
115 Kangaskhan
115 KangaskhanMega Kangaskhan
116 Horsea
117 Seadra
118 Goldeen
119 Seaking
120 Staryu
121 Starmie
122 Mr. Mime
123 Scyther
124 Jynx
125 Electabuzz
126 Magmar
127 Pinsir
127 PinsirMega Pinsir
128 Tauros
129 Magikarp
130 Gyarados
130 GyaradosMega Gyarados
131 Lapras
132 Ditto
133 Eevee
134 Vaporeon
135 Jolteon
136 Flareon
137 Porygon
138 Omanyte
139 Omastar
140 Kabuto
141 Kabutops
142 Aerodactyl
142 AerodactylMega Aerodactyl
143 Snorlax
144 Articuno
145 Zapdos
146 Moltres
147 Dratini
148 Dragonair
149 Dragonite
150 Mewtwo
150 MewtwoMega Mewtwo X
150 MewtwoMega Mewtwo Y
151 Mew
152 Chikorita
153 Bayleef
154 Meganium
155 Cyndaquil
156 Quilava
157 Typhlosion
158 Totodile
159 Croconaw
160 Feraligatr
161 Sentret
162 Furret
163 Hoothoot
164 Noctowl
165 Ledyba
166 Ledian
167 Spinarak
168 Ariados
169 Crobat
170 Chinchou
171 Lanturn
172 Pichu
173 Cleffa
174 Igglybuff
175 Togepi
176 Togetic
177 Natu
178 Xatu
179 Mareep
180 Flaaffy
181 Ampharos
181 AmpharosMega Ampharos
182 Bellossom
183 Marill
184 Azumarill
185 Sudowoodo
186 Politoed
187 Hoppip
188 Skiploom
189 Jumpluff
190 Aipom
191 Sunkern
192 Sunflora
193 Yanma
194 Wooper
195 Quagsire
196 Espeon
197 Umbreon
198 Murkrow
199 Slowking
200 Misdreavus
201 Unown
202 Wobbuffet
203 Girafarig
204 Pineco
205 Forretress
206 Dunsparce
207 Gligar
208 Steelix
208 SteelixMega Steelix
209 Snubbull
210 Granbull
211 Qwilfish
212 Scizor
212 ScizorMega Scizor
213 Shuckle
214 Heracross
214 HeracrossMega Heracross
215 Sneasel
216 Teddiursa
217 Ursaring
218 Slugma
219 Magcargo
220 Swinub
221 Piloswine
222 Corsola
223 Remoraid
224 Octillery
225 Delibird
226 Mantine
227 Skarmory
228 Houndour
229 Houndoom
229 HoundoomMega Houndoom
230 Kingdra
231 Phanpy
232 Donphan
233 Porygon2
234 Stantler
235 Smeargle
236 Tyrogue
237 Hitmontop
238 Smoochum
239 Elekid
240 Magby
241 Miltank
242 Blissey
243 Raikou
244 Entei
245 Suicune
246 Larvitar
247 Pupitar
248 Tyranitar
248 TyranitarMega Tyranitar
249 Lugia
250 Ho-oh
251 Celebi
252 Treecko
253 Grovyle
254 Sceptile
254 SceptileMega Sceptile
255 Torchic
256 Combusken
257 Blaziken
257 BlazikenMega Blaziken
258 Mudkip
259 Marshtomp
260 Swampert
260 SwampertMega Swampert
261 Poochyena
262 Mightyena
263 Zigzagoon
264 Linoone
265 Wurmple
266 Silcoon
267 Beautifly
268 Cascoon
269 Dustox
270 Lotad
271 Lombre
272 Ludicolo
273 Seedot
274 Nuzleaf
275 Shiftry
276 Taillow
277 Swellow
278 Wingull
279 Pelipper
280 Ralts
281 Kirlia
282 Gardevoir
282 GardevoirMega Gardevoir
283 Surskit
284 Masquerain
285 Shroomish
286 Breloom
287 Slakoth
288 Vigoroth
289 Slaking
290 Nincada
291 Ninjask
292 Shedinja
293 Whismur
294 Loudred
295 Exploud
296 Makuhita
297 Hariyama
298 Azurill
299 Nosepass
300 Skitty
301 Delcatty
302 Sableye
302 SableyeMega Sableye
303 Mawile
303 MawileMega Mawile
304 Aron
305 Lairon
306 Aggron
306 AggronMega Aggron
307 Meditite
308 Medicham
308 MedichamMega Medicham
309 Electrike
310 Manectric
310 ManectricMega Manectric
311 Plusle
312 Minun
313 Volbeat
314 Illumise
315 Roselia
316 Gulpin
317 Swalot
318 Carvanha
319 Sharpedo
319 SharpedoMega Sharpedo
320 Wailmer
321 Wailord
322 Numel
323 Camerupt
323 CameruptMega Camerupt
324 Torkoal
325 Spoink
326 Grumpig
327 Spinda
328 Trapinch
329 Vibrava
330 Flygon
331 Cacnea
332 Cacturne
333 Swablu
334 Altaria
334 AltariaMega Altaria
335 Zangoose
336 Seviper
337 Lunatone
338 Solrock
339 Barboach
340 Whiscash
341 Corphish
342 Crawdaunt
343 Baltoy
344 Claydol
345 Lileep
346 Cradily
347 Anorith
348 Armaldo
349 Feebas
350 Milotic
351 Castform
352 Kecleon
353 Shuppet
354 Banette
354 BanetteMega Banette
355 Duskull
356 Dusclops
357 Tropius
358 Chimecho
359 Absol
359 AbsolMega Absol
360 Wynaut
361 Snorunt
362 Glalie
362 GlalieMega Glalie
363 Spheal
364 Sealeo
365 Walrein
366 Clamperl
367 Huntail
368 Gorebyss
369 Relicanth
370 Luvdisc
371 Bagon
372 Shelgon
373 Salamence
373 SalamenceMega Salamence
374 Beldum
375 Metang
376 Metagross
376 MetagrossMega Metagross
377 Regirock
378 Regice
379 Registeel
380 Latias
380 LatiasMega Latias
381 Latios
381 LatiosMega Latios
382 Kyogre
382 KyogrePrimal Kyogre
383 Groudon
383 GroudonPrimal Groudon
384 Rayquaza
384 RayquazaMega Rayquaza
385 Jirachi
386 DeoxysNormal Forme
386 DeoxysAttack Forme
386 DeoxysDefense Forme
386 DeoxysSpeed Forme
387 Turtwig
388 Grotle
389 Torterra
390 Chimchar
391 Monferno
392 Infernape
393 Piplup
394 Prinplup
395 Empoleon
396 Starly
397 Staravia
398 Staraptor
399 Bidoof
400 Bibarel
401 Kricketot
402 Kricketune
403 Shinx
404 Luxio
405 Luxray
406 Budew
407 Roserade
408 Cranidos
409 Rampardos
410 Shieldon
411 Bastiodon
412 Burmy
413 WormadamPlant Cloak
413 WormadamSandy Cloak
413 WormadamTrash Cloak
414 Mothim
415 Combee
416 Vespiquen
417 Pachirisu
418 Buizel
419 Floatzel
420 Cherubi
421 Cherrim
422 Shellos
423 Gastrodon
424 Ambipom
425 Drifloon
426 Drifblim
427 Buneary
428 Lopunny
428 LopunnyMega Lopunny
429 Mismagius
430 Honchkrow
431 Glameow
432 Purugly
433 Chingling
434 Stunky
435 Skuntank
436 Bronzor
437 Bronzong
438 Bonsly
439 Mime Jr.
440 Happiny
441 Chatot
442 Spiritomb
443 Gible
444 Gabite
445 Garchomp
445 GarchompMega Garchomp
446 Munchlax
447 Riolu
448 Lucario
448 LucarioMega Lucario
449 Hippopotas
450 Hippowdon
451 Skorupi
452 Drapion
453 Croagunk
454 Toxicroak
455 Carnivine
456 Finneon
457 Lumineon
458 Mantyke
459 Snover
460 Abomasnow
460 AbomasnowMega Abomasnow
461 Weavile
462 Magnezone
463 Lickilicky
464 Rhyperior
465 Tangrowth
466 Electivire
467 Magmortar
468 Togekiss
469 Yanmega
470 Leafeon
471 Glaceon
472 Gliscor
473 Mamoswine
474 Porygon-Z
475 Gallade
475 GalladeMega Gallade
476 Probopass
477 Dusknoir
478 Froslass
479 Rotom
479 RotomHeat Rotom
479 RotomWash Rotom
479 RotomFrost Rotom
479 RotomFan Rotom
479 RotomMow Rotom
480 Uxie
481 Mesprit
482 Azelf
483 Dialga
484 Palkia
485 Heatran
486 Regigigas
487 GiratinaAltered Forme
487 GiratinaOrigin Forme
488 Cresselia
489 Phione
490 Manaphy
491 Darkrai
492 ShayminLand Forme
492 ShayminSky Forme
493 Arceus
494 Victini
495 Snivy
496 Servine
497 Serperior
498 Tepig
499 Pignite
500 Emboar
501 Oshawott
502 Dewott
503 Samurott
504 Patrat
505 Watchog
506 Lillipup
507 Herdier
508 Stoutland
509 Purrloin
510 Liepard
511 Pansage
512 Simisage
513 Pansear
514 Simisear
515 Panpour
516 Simipour
517 Munna
518 Musharna
519 Pidove
520 Tranquill
521 Unfezant
522 Blitzle
523 Zebstrika
524 Roggenrola
525 Boldore
526 Gigalith
527 Woobat
528 Swoobat
529 Drilbur
530 Excadrill
531 Audino
531 AudinoMega Audino
532 Timburr
533 Gurdurr
534 Conkeldurr
535 Tympole
536 Palpitoad
537 Seismitoad
538 Throh
539 Sawk
540 Sewaddle
541 Swadloon
542 Leavanny
543 Venipede
544 Whirlipede
545 Scolipede
546 Cottonee
547 Whimsicott
548 Petilil
549 Lilligant
550 Basculin
551 Sandile
552 Krokorok
553 Krookodile
554 Darumaka
555 DarmanitanStandard Mode
555 DarmanitanZen Mode
556 Maractus
557 Dwebble
558 Crustle
559 Scraggy
560 Scrafty
561 Sigilyph
562 Yamask
563 Cofagrigus
564 Tirtouga
565 Carracosta
566 Archen
567 Archeops
568 Trubbish
569 Garbodor
570 Zorua
571 Zoroark
572 Minccino
573 Cinccino
574 Gothita
575 Gothorita
576 Gothitelle
577 Solosis
578 Duosion
579 Reuniclus
580 Ducklett
581 Swanna
582 Vanillite
583 Vanillish
584 Vanilluxe
585 Deerling
586 Sawsbuck
587 Emolga
588 Karrablast
589 Escavalier
590 Foongus
591 Amoonguss
592 Frillish
593 Jellicent
594 Alomomola
595 Joltik
596 Galvantula
597 Ferroseed
598 Ferrothorn
599 Klink
600 Klang
601 Klinklang
602 Tynamo
603 Eelektrik
604 Eelektross
605 Elgyem
606 Beheeyem
607 Litwick
608 Lampent
609 Chandelure
610 Axew
611 Fraxure
612 Haxorus
613 Cubchoo
614 Beartic
615 Cryogonal
616 Shelmet
617 Accelgor
618 Stunfisk
619 Mienfoo
620 Mienshao
621 Druddigon
622 Golett
623 Golurk
624 Pawniard
625 Bisharp
626 Bouffalant
627 Rufflet
628 Braviary
629 Vullaby
630 Mandibuzz
631 Heatmor
632 Durant
633 Deino
634 Zweilous
635 Hydreigon
636 Larvesta
637 Volcarona
638 Cobalion
639 Terrakion
640 Virizion
641 TornadusIncarnate Forme
641 TornadusTherian Forme
642 ThundurusIncarnate Forme
642 ThundurusTherian Forme
643 Reshiram
644 Zekrom
645 LandorusIncarnate Forme
645 LandorusTherian Forme
646 Kyurem
646 KyuremBlack Kyurem
646 KyuremWhite Kyurem
647 KeldeoOrdinary Forme
647 KeldeoResolute Forme
648 MeloettaAria Forme
648 MeloettaPirouette Forme
649 Genesect
650 Chespin
651 Quilladin
652 Chesnaught
653 Fennekin
654 Braixen
655 Delphox
656 Froakie
657 Frogadier
658 Greninja
659 Bunnelby
660 Diggersby
661 Fletchling
662 Fletchinder
663 Talonflame
664 Scatterbug
665 Spewpa
666 Vivillon
667 Litleo
668 Pyroar
669 FlabÃ©bÃ©
670 Floette
671 Florges
672 Skiddo
673 Gogoat
674 Pancham
675 Pangoro
676 Furfrou
677 Espurr
678 MeowsticMale
678 MeowsticFemale
679 Honedge
680 Doublade
681 AegislashBlade Forme
681 AegislashShield Forme
682 Spritzee
683 Aromatisse
684 Swirlix
685 Slurpuff
686 Inkay
687 Malamar
688 Binacle
689 Barbaracle
690 Skrelp
691 Dragalge
692 Clauncher
693 Clawitzer
694 Helioptile
695 Heliolisk
696 Tyrunt
697 Tyrantrum
698 Amaura
699 Aurorus
700 Sylveon
701 Hawlucha
702 Dedenne
703 Carbink
704 Goomy
705 Sliggoo
706 Goodra
707 Klefki
708 Phantump
709 Trevenant
710 PumpkabooAverage Size
710 PumpkabooSmall Size
710 PumpkabooLarge Size
710 PumpkabooSuper Size
711 GourgeistAverage Size
711 GourgeistSmall Size
711 GourgeistLarge Size
711 GourgeistSuper Size
712 Bergmite
713 Avalugg
714 Noibat
715 Noivern
716 Xerneas
717 Yveltal
718 Zygarde50% Forme
719 Diancie
719 DiancieMega Diancie
720 HoopaHoopa Confined
720 HoopaHoopa Unbound
721 Volcanion

In [25]:
print(pokemon_data.loc[pokemon_data['Type 1'] == 'Grass'])
# More priority to the labels.

                      Name Type 1    Type 2   HP  Attack  Defense  Sp. Atk  \
#
1                Bulbasaur  Grass    Poison   45      49       49       65
2                  Ivysaur  Grass    Poison   60      62       63       80
3                 Venusaur  Grass    Poison   80      82       83      100
3    VenusaurMega Venusaur  Grass    Poison   80     100      123      122
43                  Oddish  Grass    Poison   45      50       55       75
..                     ...    ...       ...  ...     ...      ...      ...
650                Chespin  Grass       NaN   56      61       65       48
651              Quilladin  Grass       NaN   61      78       95       56
652             Chesnaught  Grass  Fighting   88     107      122       74
672                 Skiddo  Grass       NaN   66      65       48       62
673                 Gogoat  Grass       NaN  123     100       62       97

     Sp. Def  Speed  Generation  Legendary
#
1         65     45           1      False
2         80     60           1      False
3        100     80           1      False
3        120     80           1      False
43        65     30           1      False
..       ...    ...         ...        ...
650       45     38           6      False
651       58     57           6      False
652       75     64           6      False
672       57     52           6      False
673       81     68           6      False

[70 rows x 11 columns]

In [35]:
# Sorting / Describing Data
pokemon_data.describe()
# Gives you all kinds of data that you are looking for.
pokemon_data.sort_values(['Type 1' , 'HP'] , ascending=[1,0])

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...
98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [ ]:
pokemon_data.head(5)

Making Changes in the data

In [37]:
pokemon_data['Total'] = pokemon_data['HP'] + pokemon_data['Attack'] + pokemon_data['Defense'] + pokemon_data['Sp. Atk'] + pokemon_data['Sp. Def'] + pokemon_data['Speed']
pokemon_data.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [38]:
# Dropping or Deleting a Column from database
pokemon_data = pokemon_data.drop(columns=['Total'])
pokemon_data

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [39]:
pokemon_data['Total'] = pokemon_data.iloc[:, 4:10].sum(axis=1)

pokemon_data.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,274
2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,346
3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,446
3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,546
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,271

In [42]:
cols = list(pokemon_data.columns.values)

# We are changing the position to the column "Total"
pokemon_data = pokemon_data[cols[0:4] + [cols[-1]] + cols[4:12]]
pokemon_data

,Name,Type 1,Type 2,HP,Total,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,274,49,49,65,65,45,1,False,274
2,Ivysaur,Grass,Poison,60,346,62,63,80,80,60,1,False,346
3,Venusaur,Grass,Poison,80,446,82,83,100,100,80,1,False,446
3,VenusaurMega Venusaur,Grass,Poison,80,546,100,123,122,120,80,1,False,546
4,Charmander,Fire,NaN,39,271,52,43,60,50,65,1,False,271
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,556,100,150,100,150,50,6,True,556
719,DiancieMega Diancie,Rock,Fairy,50,656,160,110,160,110,110,6,True,656
720,HoopaHoopa Confined,Psychic,Ghost,80,526,110,60,150,130,70,6,True,526
720,HoopaHoopa Unbound,Psychic,Dark,80,606,160,60,170,130,80,6,True,606
721,Volcanion,Fire,Water,80,526,110,120,130,90,70,6,True,526

In [ ]:
# Saving or Creating a new csv file
# You can create .xlsx , .txt , .csv
pokemon_data.to_csv("modified.txt" , index=False)  

pokemon_data.to_excel('modified.xlsx' , index=False)

pokemon_data.to_csv('modified.csv',index=False)

In [48]:
# Filtering Data
# Showing only rows which has grass.

new_df = pokemon_data.loc[(pokemon_data['Type 1'] == 'Grass') & (pokemon_data['Type 2'] == "Poison") & (pokemon_data['HP'] > 70)]

# Resetting the indices of the rows after selecting data from the main csv file
new_df = new_df.reset_index()
# OR
new_df.reset_index(drop=True , inplace =True)

,#,Name,Type 1,Type 2,HP,Total,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,3,Venusaur,Grass,Poison,80,446,82,83,100,100,80,1,False,446
1,3,VenusaurMega Venusaur,Grass,Poison,80,546,100,123,122,120,80,1,False,546
2,45,Vileplume,Grass,Poison,75,416,80,85,110,90,50,1,False,416
3,71,Victreebel,Grass,Poison,80,411,105,65,100,70,70,1,False,411
4,591,Amoonguss,Grass,Poison,114,355,85,70,85,80,30,5,False,355

In [51]:
# This willhelps us to get names containing "Mega"
pokemon_data.loc[pokemon_data['Name'].str.contains('Mega')]

# This ~ will removes all the names containing 'Mega'
pokemon_data.loc[~pokemon_data['Name'].str.contains('Mega')]

,Name,Type 1,Type 2,HP,Total,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,274,49,49,65,65,45,1,False,274
2,Ivysaur,Grass,Poison,60,346,62,63,80,80,60,1,False,346
3,Venusaur,Grass,Poison,80,446,82,83,100,100,80,1,False,446
4,Charmander,Fire,NaN,39,271,52,43,60,50,65,1,False,271
5,Charmeleon,Fire,NaN,58,348,64,58,80,65,80,1,False,348
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,Zygarde50% Forme,Dragon,Ground,108,498,100,121,81,95,95,6,True,498
719,Diancie,Rock,Fairy,50,556,100,150,100,150,50,6,True,556
720,HoopaHoopa Confined,Psychic,Ghost,80,526,110,60,150,130,70,6,True,526
720,HoopaHoopa Unbound,Psychic,Dark,80,606,160,60,170,130,80,6,True,606
721,Volcanion,Fire,Water,80,526,110,120,130,90,70,6,True,526

In [54]:
# Regex Filtering
import re

# pokemon_data.loc[pokemon_data['Type 1'].str.contains('Fire|Grass', flags=re.I , regex=True)]

pokemon_data.loc[pokemon_data['Name'].str.contains('^pi[a-z]*', flags=re.I , regex=True)]

,Name,Type 1,Type 2,HP,Total,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
#,,,,,,,,,,,,,
16,Pidgey,Normal,Flying,40,212,45,40,35,35,56,1,False,212
17,Pidgeotto,Normal,Flying,63,287,60,55,50,50,71,1,False,287
18,Pidgeot,Normal,Flying,83,397,80,75,70,70,101,1,False,397
18,PidgeotMega Pidgeot,Normal,Flying,83,497,80,80,135,80,121,1,False,497
25,Pikachu,Electric,NaN,35,286,55,40,50,50,90,1,False,286
127,Pinsir,Bug,NaN,65,436,125,100,55,70,85,1,False,436
127,PinsirMega Pinsir,Bug,Flying,65,536,155,120,65,90,105,1,False,536
172,Pichu,Electric,NaN,20,187,40,15,35,35,60,2,False,187
204,Pineco,Bug,NaN,50,242,65,90,35,35,15,2,False,242
221,Piloswine,Ice,Ground,100,352,100,80,60,60,50,2,False,352
393,Piplup,Water,NaN,53,265,51,53,61,56,40,4,False,265
499,Pignite,Fire,Fighting,90,333,93,55,70,55,55,5,False,333
519,Pidove,Normal,Flying,50,219,55,50,36,30,43,5,False,219

In [57]:
# Conditional Changes
# Converting Fire into Flamer
pokemon_data.loc[pokemon_data['Type 1'] == 'Fire' , 'Type 1'] = 'Flamer'
pokemon_data

C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,Name,Type 1,Type 2,HP,Total,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,45,274,49,49,65,65,45,1,False,274
2,Ivysaur,Grass,Poison,60,346,62,63,80,80,60,1,False,346
3,Venusaur,Grass,Poison,80,446,82,83,100,100,80,1,False,446
3,VenusaurMega Venusaur,Grass,Poison,80,546,100,123,122,120,80,1,False,546
4,Charmander,Flamer,NaN,39,271,52,43,60,50,65,1,False,271
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,50,556,100,150,100,150,50,6,True,556
719,DiancieMega Diancie,Rock,Fairy,50,656,160,110,160,110,110,6,True,656
720,HoopaHoopa Confined,Psychic,Ghost,80,526,110,60,150,130,70,6,True,526
720,HoopaHoopa Unbound,Psychic,Dark,80,606,160,60,170,130,80,6,True,606
721,Volcanion,Flamer,Water,80,526,110,120,130,90,70,6,True,526

In [8]:
# Aggegarte Statistics (GroupBy)
# sum , mean , count
df = pd.read_csv('pokemon_data.csv')

df.groupby(['Type 1']).mean().sort_values('Attack' , ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824

In [10]:
df['count'] = 1

df.groupby(['Type 1' , 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64